version: 2

updates:
  # Auto-upgrade GitHub Actions versions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
    # Add labels manually due to Dependabot secrets issues
    # see https://github.com/dependabot/dependabot-core/issues/3253
      - "kind/dependency"
      - "area/automation"
      - "bump:patch"

  # Auto-upgrade Terraform module versions
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
    # Add labels manually due to Dependabot secrets issues
    # see https://github.com/dependabot/dependabot-core/issues/3253
      - "kind/dependency"
      - "area/automation"
      - "area/terraform"
      - "bump:minor"
