repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_validate
        args:
          - '--envs=AWS_DEFAULT_REGION="eu-west-1"'
      - id: terraform_fmt
      - id: terraform_docs
        args: ['--args=--sort-by required']
      - id: terraform_tflint
        args:
          - 'args=--module'
      - id: terraform_tfsec
