name: Conformance

on:
  pull_request:
    types: [opened, synchronize, edited, labeled, unlabeled]

jobs:
  Labels:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Assign content labels
        if: github.actor != 'dependabot[bot]'
        # Labels are added manually in .github/dependabot.yml
        #  due to Dependabot secrets issues
        #  see https://github.com/dependabot/dependabot-core/issues/3253
        uses: actions/labeler@v3
        with:
          configuration-path: .github/auto-label.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Assign size label
        uses: pascalgn/size-label-action@v0.4.3
        if: github.actor != 'dependabot[bot]'
        # Skip the size label due to due to Dependabot secrets issues
        #  see https://github.com/dependabot/dependabot-core/issues/3253
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
